import { Router, type IRouter } from "express";
import healthRouter from "./health";
import botRouter from "./bot";
import tradesRouter from "./trades";
import analyticsRouter from "./analytics";
import marketRouter from "./market";
import learningRouter from "./learning";
import backtestRouter from "./backtest";
import brokerRouter from "./broker";
import newsRouter from "./news";
import regimeRouter from "./regime";
import montecarloRouter from "./montecarlo";
import paperRouter from "./paper";
import qualityRouter from "./quality";
import memoryRouter from "./memory";
import supervisorRouter from "./supervisor";
import v2Router from "./v2";
import reportsRouter from "./reports";
import replayRouter from "./replay";
import historicalRouter from "./historical";
import productionReadinessRouter from "./production-readiness";
import deploymentRouter from "./deployment";
import readinessChecklistRouter from "./readiness-checklist";
import liveJournalRouter from "./live-journal";
import robustnessRouter from "./robustness";
import traderIntelligenceRouter from "./trader-intelligence";
import paperConfigRouter from "./paper-config";
import thresholdRouter from "./threshold";
import pilotRouter from "./pilot";
import improvementRouter from "./improvement";
import paperWorkspaceRouter from "./paper-workspace";
import memoryHealthRouter from "./memory-health";
import learningEngineRouter from "./learning-engine";
import patternPerformanceRouter from "./pattern-performance";
import featureImportanceRouter from "./feature-importance";
import { decisionIntelligenceRouter } from "./decision-intelligence";
import learningHealthRouter from "./learning-health";

const router: IRouter = Router();

router.use(healthRouter);
router.use(botRouter);
router.use(tradesRouter);
router.use(analyticsRouter);
router.use(marketRouter);
router.use(learningRouter);
router.use(backtestRouter);
router.use(brokerRouter);
router.use(newsRouter);
router.use(regimeRouter);
router.use(montecarloRouter);
router.use(paperRouter);
router.use(paperConfigRouter);
router.use(qualityRouter);
router.use(memoryRouter);
router.use(supervisorRouter);
router.use(v2Router);
router.use(reportsRouter);
router.use(replayRouter);
router.use(historicalRouter);
router.use(productionReadinessRouter);
router.use(deploymentRouter);
router.use(readinessChecklistRouter);
router.use(liveJournalRouter);
router.use(robustnessRouter);
router.use(traderIntelligenceRouter);
router.use(thresholdRouter);
router.use(pilotRouter);
router.use(improvementRouter);
router.use(paperWorkspaceRouter);
router.use(memoryHealthRouter);
router.use(learningEngineRouter);
router.use(patternPerformanceRouter);
router.use(featureImportanceRouter);
router.use(decisionIntelligenceRouter);
router.use(learningHealthRouter);

export default router;
