import { pgTable, text, integer, timestamp, jsonb, uuid } from "drizzle-orm/pg-core";

export const marketStateSnapshotsTable = pgTable("market_state_snapshots", {
  id: uuid("id").defaultRandom().primaryKey(),
  pair: text("pair").notNull(),
  session: text("session").notNull(),
  trendDirection: text("trend_direction").notNull(),
  trendStrength: integer("trend_strength").notNull().default(0),
  trendPersistence: integer("trend_persistence").notNull().default(0),
  trendAge: integer("trend_age").notNull().default(0),
  regime: text("regime").notNull(),
  regimeConfidence: integer("regime_confidence").notNull().default(0),
  volatilityClassification: text("volatility_classification").notNull(),
  volatilityPercentile: integer("volatility_percentile").notNull().default(50),
  volatilityTrend: text("volatility_trend").notNull().default("stable"),
  atr: text("atr").notNull().default("0"),
  historicalVolatility: text("historical_volatility").notNull().default("0"),
  realizedVolatility: text("realized_volatility").notNull().default("0"),
  liquidityQuality: text("liquidity_quality").notNull(),
  liquidityScore: integer("liquidity_score").notNull().default(0),
  relativeVolume: text("relative_volume").notNull().default("1"),
  correlationRisk: text("correlation_risk").notNull().default("low"),
  newsEnvironment: text("news_environment").notNull().default("safe"),
  nextEventMinutes: integer("next_event_minutes"),
  overallConfidence: text("overall_confidence").notNull(),
  confidenceScore: integer("confidence_score").notNull().default(0),
  summary: text("summary").notNull().default(""),
  fullState: jsonb("full_state"),
  createdAt: timestamp("created_at").defaultNow(),
});
