// ─── Autonomous Research & Self-Evolution Laboratory — DB Schema ──────────────
// All research is sandboxed. No table here touches production trade execution.

import {
  pgTable, text, integer, boolean, timestamp, uuid, jsonb, decimal, index,
} from "drizzle-orm/pg-core";

// ─── Research Projects ────────────────────────────────────────────────────────
// A high-level research initiative targeting a specific weakness or improvement.

export const rlProjectsTable = pgTable("rl_projects", {
  projectId:       uuid("project_id").primaryKey().defaultRandom(),
  version:         text("version").notNull(),
  title:           text("title").notNull(),
  description:     text("description").notNull(),
  objective:       text("objective").notNull(),
  weaknessTarget:  text("weakness_target").notNull(),
  status:          text("status").notNull(),          // active | paused | completed | archived
  priority:        text("priority").notNull(),         // critical | high | medium | low
  hypothesisCount: integer("hypothesis_count").notNull().default(0),
  experimentCount: integer("experiment_count").notNull().default(0),
  isAdvisoryOnly:  boolean("is_advisory_only").notNull().default(true),
  startedAt:       timestamp("started_at").notNull(),
  completedAt:     timestamp("completed_at"),
  createdAt:       timestamp("created_at").notNull().defaultNow(),
}, t => [index("rl_projects_status_idx").on(t.status)]);

// ─── Research Hypotheses ──────────────────────────────────────────────────────
// An improvement hypothesis generated by the research engine.

export const rlHypothesesTable = pgTable("rl_hypotheses", {
  hypothesisId:       uuid("hypothesis_id").primaryKey().defaultRandom(),
  projectId:          uuid("project_id").notNull(),
  version:            text("version").notNull(),
  title:              text("title").notNull(),
  description:        text("description").notNull(),
  rationale:          text("rationale").notNull(),
  weaknessId:         text("weakness_id"),
  hypothesisType:     text("hypothesis_type").notNull(), // rule_change | threshold_change | feature_addition | model_change | filter_change
  targetComponent:    text("target_component").notNull(),
  proposedChange:     jsonb("proposed_change").notNull().$type<Record<string, unknown>>(),
  expectedImprovement:decimal("expected_improvement", { precision: 6, scale: 2 }).notNull(),
  confidenceScore:    decimal("confidence_score", { precision: 6, scale: 2 }).notNull(),
  supportingEvidence: jsonb("supporting_evidence").notNull().$type<string[]>(),
  status:             text("status").notNull(), // pending | testing | validated | rejected | archived
  experimentId:       uuid("experiment_id"),
  createdAt:          timestamp("created_at").notNull().defaultNow(),
}, t => [index("rl_hypotheses_project_idx").on(t.projectId)]);

// ─── Research Experiments ─────────────────────────────────────────────────────
// An experimental strategy version — completely isolated from production.

export const rlExperimentsTable = pgTable("rl_experiments", {
  experimentId:         uuid("experiment_id").primaryKey().defaultRandom(),
  projectId:            uuid("project_id").notNull(),
  hypothesisId:         uuid("hypothesis_id"),
  version:              text("version").notNull(),
  name:                 text("name").notNull(),
  description:          text("description").notNull(),
  parentVersion:        text("parent_version").notNull(),
  strategyVersion:      text("strategy_version").notNull(),
  researchObjective:    text("research_objective").notNull(),
  configChanges:        jsonb("config_changes").notNull().$type<Record<string, unknown>>(),
  status:               text("status").notNull(), // building | running | validating | completed | failed | rejected
  validationStage:      text("validation_stage"),  // which pipeline stage is active
  validationResults:    jsonb("validation_results").$type<Record<string, unknown>>(),
  performanceMetrics:   jsonb("performance_metrics").$type<Record<string, unknown>>(),
  statisticalConfidence:decimal("statistical_confidence", { precision: 6, scale: 2 }),
  approvalStatus:       text("approval_status").notNull().default("pending"), // pending | approved | rejected | archived
  deploymentStatus:     text("deployment_status").notNull().default("not_deployed"),
  isSandboxed:          boolean("is_sandboxed").notNull().default(true),
  isAdvisoryOnly:       boolean("is_advisory_only").notNull().default(true),
  startedAt:            timestamp("started_at").notNull(),
  completedAt:          timestamp("completed_at"),
  createdAt:            timestamp("created_at").notNull().defaultNow(),
}, t => [
  index("rl_experiments_project_idx").on(t.projectId),
  index("rl_experiments_status_idx").on(t.status),
]);

// ─── Code Changes ─────────────────────────────────────────────────────────────
// Version-controlled research code change artifacts (research env only).

export const rlCodeChangesTable = pgTable("rl_code_changes", {
  changeId:        uuid("change_id").primaryKey().defaultRandom(),
  experimentId:    uuid("experiment_id").notNull(),
  projectId:       uuid("project_id").notNull(),
  changeType:      text("change_type").notNull(),       // refactor | new_algorithm | filter | scoring | feature | optimization
  targetModule:    text("target_module").notNull(),
  changeTitle:     text("change_title").notNull(),
  description:     text("description").notNull(),
  rationale:       text("rationale").notNull(),
  pseudoCode:      text("pseudo_code"),
  configBefore:    jsonb("config_before").$type<Record<string, unknown>>(),
  configAfter:     jsonb("config_after").$type<Record<string, unknown>>(),
  linesAdded:      integer("lines_added").notNull().default(0),
  linesRemoved:    integer("lines_removed").notNull().default(0),
  testsPassed:     boolean("tests_passed").notNull().default(false),
  staticAnalysis:  boolean("static_analysis").notNull().default(false),
  securityCheck:   boolean("security_check").notNull().default(false),
  perfBenchmark:   boolean("perf_benchmark").notNull().default(false),
  affectsProduction: boolean("affects_production").notNull().default(false),
  isResearchOnly:  boolean("is_research_only").notNull().default(true),
  createdAt:       timestamp("created_at").notNull().defaultNow(),
}, t => [index("rl_code_changes_experiment_idx").on(t.experimentId)]);

// ─── Performance Comparisons ──────────────────────────────────────────────────
// Statistical comparison between production and experimental strategy.

export const rlComparisonsTable = pgTable("rl_comparisons", {
  comparisonId:       uuid("comparison_id").primaryKey().defaultRandom(),
  experimentId:       uuid("experiment_id").notNull(),
  projectId:          uuid("project_id").notNull(),
  productionVersion:  text("production_version").notNull(),
  experimentVersion:  text("experiment_version").notNull(),
  sampleSize:         integer("sample_size").notNull(),
  testPeriodDays:     integer("test_period_days").notNull(),

  // Production metrics
  prodWinRate:        decimal("prod_win_rate", { precision: 6, scale: 4 }).notNull(),
  prodAvgRr:          decimal("prod_avg_rr", { precision: 6, scale: 3 }).notNull(),
  prodProfitFactor:   decimal("prod_profit_factor", { precision: 6, scale: 3 }).notNull(),
  prodMaxDrawdown:    decimal("prod_max_drawdown", { precision: 6, scale: 4 }).notNull(),
  prodSharpe:         decimal("prod_sharpe", { precision: 6, scale: 3 }).notNull(),
  prodTotalReturn:    decimal("prod_total_return", { precision: 8, scale: 4 }).notNull(),

  // Experimental metrics
  expWinRate:         decimal("exp_win_rate", { precision: 6, scale: 4 }).notNull(),
  expAvgRr:           decimal("exp_avg_rr", { precision: 6, scale: 3 }).notNull(),
  expProfitFactor:    decimal("exp_profit_factor", { precision: 6, scale: 3 }).notNull(),
  expMaxDrawdown:     decimal("exp_max_drawdown", { precision: 6, scale: 4 }).notNull(),
  expSharpe:          decimal("exp_sharpe", { precision: 6, scale: 3 }).notNull(),
  expTotalReturn:     decimal("exp_total_return", { precision: 8, scale: 4 }).notNull(),

  // Statistical tests
  winRatePValue:      decimal("win_rate_p_value", { precision: 8, scale: 6 }),
  sharpeImprovement:  decimal("sharpe_improvement", { precision: 6, scale: 4 }),
  isStatSignificant:  boolean("is_stat_significant").notNull().default(false),
  overallVerdict:     text("overall_verdict").notNull(), // superior | equivalent | inferior
  verdictScore:       decimal("verdict_score", { precision: 6, scale: 2 }).notNull(),
  summary:            text("summary").notNull(),

  createdAt:          timestamp("created_at").notNull().defaultNow(),
}, t => [index("rl_comparisons_experiment_idx").on(t.experimentId)]);

// ─── Deployment Recommendations ───────────────────────────────────────────────
// Evidence-based recommendation to deploy an experimental version.

export const rlRecommendationsTable = pgTable("rl_recommendations", {
  recommendationId:     uuid("recommendation_id").primaryKey().defaultRandom(),
  experimentId:         uuid("experiment_id").notNull(),
  projectId:            uuid("project_id").notNull(),
  comparisonId:         uuid("comparison_id"),
  version:              text("version").notNull(),
  title:                text("title").notNull(),
  summary:              text("summary").notNull(),
  codeChangeSummary:    text("code_change_summary").notNull(),
  performanceSummary:   text("performance_summary").notNull(),
  riskAssessment:       text("risk_assessment").notNull(),
  statisticalSignificance: decimal("statistical_significance", { precision: 6, scale: 4 }).notNull(),
  confidenceScore:      decimal("confidence_score", { precision: 6, scale: 2 }).notNull(),
  validationEvidence:   jsonb("validation_evidence").notNull().$type<string[]>(),
  potentialDrawbacks:   jsonb("potential_drawbacks").notNull().$type<string[]>(),
  rollbackPlan:         text("rollback_plan").notNull(),
  recommendationType:   text("recommendation_type").notNull(), // deploy | continue_testing | archive | rollback
  status:               text("status").notNull(), // pending_approval | approved | rejected | archived
  createdAt:            timestamp("created_at").notNull().defaultNow(),
}, t => [index("rl_recommendations_experiment_idx").on(t.experimentId)]);

// ─── Approval Queue ───────────────────────────────────────────────────────────
// Human approval workflow items.

export const rlApprovalQueueTable = pgTable("rl_approval_queue", {
  queueId:          uuid("queue_id").primaryKey().defaultRandom(),
  recommendationId: uuid("recommendation_id").notNull(),
  experimentId:     uuid("experiment_id").notNull(),
  projectId:        uuid("project_id").notNull(),
  title:            text("title").notNull(),
  summary:          text("summary").notNull(),
  priority:         text("priority").notNull(),
  requestedAt:      timestamp("requested_at").notNull(),
  decidedAt:        timestamp("decided_at"),
  decision:         text("decision"), // approved | rejected | more_testing | continue_paper | archived
  decisionReason:   text("decision_reason"),
  decidedBy:        text("decided_by"),
  status:           text("status").notNull(), // pending | decided | expired
  expiresAt:        timestamp("expires_at"),
  createdAt:        timestamp("created_at").notNull().defaultNow(),
}, t => [index("rl_approval_queue_status_idx").on(t.status)]);

// ─── Research History ─────────────────────────────────────────────────────────
// Full reproducible audit log of all research events.

export const rlHistoryTable = pgTable("rl_history", {
  historyId:    uuid("history_id").primaryKey().defaultRandom(),
  eventType:    text("event_type").notNull(),  // project_created | hypothesis_generated | experiment_started | validation_passed | validation_failed | comparison_complete | recommendation_created | approval_requested | approved | rejected | deployed | rolled_back
  entityType:   text("entity_type").notNull(), // project | hypothesis | experiment | comparison | recommendation | approval
  entityId:     uuid("entity_id").notNull(),
  projectId:    uuid("project_id"),
  title:        text("title").notNull(),
  description:  text("description").notNull(),
  metadata:     jsonb("metadata").$type<Record<string, unknown>>(),
  isReproducible: boolean("is_reproducible").notNull().default(true),
  createdAt:    timestamp("created_at").notNull().defaultNow(),
}, t => [
  index("rl_history_event_idx").on(t.eventType),
  index("rl_history_entity_idx").on(t.entityId),
]);
